# THIS FILE WAS GENERATED BY `xtp-python-bindgen`. DO NOT EDIT.

from typing import Optional, List  # noqa: F401
from datetime import datetime  # noqa: F401
import json
import extism  # pyright: ignore
import plugin


from pdk_types import (
    ColumnInfo,
    DatabaseStats,
    EmptyInput,
    EnhancedSqlParams,
    EnhancedSqlResult,
    IndexInfo,
    KvReadInput,
    KvStoreInput,
    PerformanceSummary,
    QueryExplanation,
    QueryMetadata,
    SqliteTestResult,
    TableInfo,
    TableNameInput,
    TestStepResult,
    TransactionIdInput,
    TransactionResult,
    TypedSqlParam,
)  # noqa: F401


# Imports


# kv_read Read a JSON value from the key-value database
# It takes input of KvReadInput ()
# And it returns an output Optional[dict] (The stored JSON value, or null if not found)
@extism.import_fn("extism:host/user", "kv_read")
def _kv_read(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# kv_store Store a JSON value in the key-value database
# It takes input of KvStoreInput ()
# And it returns an output bool (No return value - operation success indicated by lack of error)
@extism.import_fn("extism:host/user", "kv_store")
def _kv_store(input: str) -> bytes:  # pyright: ignore [reportReturnType]
    pass


# sqlite_begin_transaction Begin a database transaction
# It takes input of EmptyInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_begin_transaction")
def _sqlite_begin_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_commit_transaction Commit a database transaction
# It takes input of TransactionIdInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_commit_transaction")
def _sqlite_commit_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_describe_table Get detailed information about a table structure
# It takes input of TableNameInput ()
# And it returns an output TableInfo ()
@extism.import_fn("extism:host/user", "sqlite_describe_table")
def _sqlite_describe_table(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_execute_enhanced Execute a SQL statement with enhanced metadata and type support
# It takes input of EnhancedSqlParams ()
# And it returns an output EnhancedSqlResult ()
@extism.import_fn("extism:host/user", "sqlite_execute_enhanced")
def _sqlite_execute_enhanced(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_explain_query Get query execution plan for debugging and optimization
# It takes input of EnhancedSqlParams ()
# And it returns an output QueryExplanation ()
@extism.import_fn("extism:host/user", "sqlite_explain_query")
def _sqlite_explain_query(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_get_stats Get database performance statistics
# It takes input of EmptyInput ()
# And it returns an output DatabaseStats ()
@extism.import_fn("extism:host/user", "sqlite_get_stats")
def _sqlite_get_stats(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_list_tables List all tables in the database
# It takes input of EmptyInput ()
# And it returns an output str (JSON array of table names)
@extism.import_fn("extism:host/user", "sqlite_list_tables")
def _sqlite_list_tables(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_query_enhanced Execute a SQL query with enhanced metadata and type support
# It takes input of EnhancedSqlParams ()
# And it returns an output EnhancedSqlResult ()
@extism.import_fn("extism:host/user", "sqlite_query_enhanced")
def _sqlite_query_enhanced(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# sqlite_rollback_transaction Rollback a database transaction
# It takes input of TransactionIdInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_rollback_transaction")
def _sqlite_rollback_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


# Exports
# The implementations for these functions is in `plugin.py`


# Test entry point that demonstrates all SQLite functionality
@extism.plugin_fn
def testEnhancedSql():
    input = extism.input_str()
    res = plugin.test_enhanced_sql(input)
    extism.output_str(res.to_json())
