# THIS FILE WAS GENERATED BY `xtp-python-bindgen`. DO NOT EDIT.

from __future__ import annotations
from enum import Enum  # noqa: F401
from typing import Optional, List  # noqa: F401
from datetime import datetime  # noqa: F401
from dataclasses import dataclass  # noqa: F401
from dataclass_wizard import JSONWizard, skip_if_field, IS  # noqa: F401
from dataclass_wizard.type_def import JSONObject
from base64 import b64encode, b64decode


@dataclass
class ColumnInfo(JSONWizard):
    # Whether this column auto-increments
    autoIncrement: bool

    # Column name
    name: str

    # Whether the column can contain NULL values
    nullable: bool

    # Whether this column is part of the primary key
    primaryKey: bool

    # Column SQL type (e.g., TEXT, INTEGER, REAL)
    type: str

    # Default value for the column
    defaultValue: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class DatabaseStats(JSONWizard):
    # Average execution time per query
    averageExecutionTimeMs: float

    # Database size in bytes
    databaseSizeBytes: int

    # Count of queries by type (SELECT, INSERT, etc.)
    queryCountByType: dict

    # SQLite version string
    sqliteVersion: str

    # Total execution time across all queries
    totalExecutionTimeMs: float

    # Total number of queries executed
    totalQueries: int

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class EmptyInput(JSONWizard):
    # Dummy field to satisfy schema requirements
    _dummy: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class EnhancedSqlParams(JSONWizard):
    # Array of typed SQL parameters
    params: List[TypedSqlParam]

    # The SQL statement or query to execute
    sql: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class EnhancedSqlResult(JSONWizard):
    # Information about result columns
    columns: List[ColumnInfo]

    # Array of result rows as JSON objects
    data: List[dict]

    # Query execution metadata
    metadata: QueryMetadata

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class IndexInfo(JSONWizard):
    # Columns included in the index
    columns: List[str]

    # Index name
    name: str

    # Whether this is a unique index
    unique: bool

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class KvReadInput(JSONWizard):
    # The key to read the value for
    key: str

    # The table name to read from
    table: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class KvStoreInput(JSONWizard):
    # The key to store the value under
    key: str

    # The table name to store the value in
    table: str

    # The JSON value to store
    value: dict

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class PerformanceSummary(JSONWizard):
    # Average execution time per query
    averageQueryTimeMs: float

    # List of database operations performed
    databaseOperations: List[str]

    # Total time for all operations
    totalExecutionTimeMs: float

    # Total number of SQL operations performed
    totalQueries: int

    # The fastest database operation
    fastestOperation: Optional[str] = skip_if_field(IS(None), default=None)

    # The slowest database operation
    slowestOperation: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class QueryExplanation(JSONWizard):
    # Estimated query cost (if available)
    estimatedCost: float

    # Estimated number of rows (if available)
    estimatedRows: int

    # Human-readable query execution plan
    queryPlan: str

    # SQLite version string
    sqliteVersion: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class QueryMetadata(JSONWizard):
    # Query execution time in milliseconds
    executionTimeMs: float

    # Number of rows affected by the statement
    rowsAffected: int

    # Number of rows returned by the query
    rowsReturned: int

    # SQLite version string
    sqliteVersion: str

    # Row ID of the last inserted row (for INSERT statements)
    lastInsertRowid: Optional[int] = skip_if_field(IS(None), default=None)

    # SQLite query execution plan
    queryPlan: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class SqliteTestResult(JSONWizard):
    # Overall performance metrics
    performanceSummary: PerformanceSummary

    # Individual test results
    results: List[TestStepResult]

    # Whether all tests passed successfully
    success: bool

    # Name of the test that was executed
    testName: str

    # Error message if test failed
    errorMessage: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TableInfo(JSONWizard):
    # Table columns
    columns: List[ColumnInfo]

    # Table indexes
    indexes: List[IndexInfo]

    # Table name
    name: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TableNameInput(JSONWizard):
    # Name of the table
    tableName: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TestStepResult(JSONWizard):
    # Time taken for this step
    executionTimeMs: float

    # Name of the test step
    stepName: str

    # Whether this step passed
    success: bool

    # Additional details about the test step
    details: Optional[dict] = skip_if_field(IS(None), default=None)

    # Error message if step failed
    errorMessage: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TransactionIdInput(JSONWizard):
    # Transaction identifier
    transactionId: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TransactionResult(JSONWizard):
    # Whether the transaction operation succeeded
    success: bool

    # Transaction identifier
    transactionId: str

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return


@dataclass
class TypedSqlParam(JSONWizard):
    # The parameter value (can be string, number, boolean, null, etc.)
    value: dict

    # Optional type hint for the parameter
    typeHint: Optional[str] = skip_if_field(IS(None), default=None)

    @classmethod
    def _pre_from_dict(cls, o: JSONObject) -> JSONObject:
        return o

    def _pre_dict(self):
        return
