# THIS FILE WAS GENERATED BY `xtp-python-bindgen`. DO NOT EDIT.

from typing import Optional, List  # noqa: F401
from datetime import datetime  # noqa: F401
import extism  # noqa: F401 # pyright: ignore
import json


from pdk_types import (
    ColumnInfo,
    DatabaseStats,
    EmptyInput,
    EnhancedSqlParams,
    EnhancedSqlResult,
    IndexInfo,
    KvReadInput,
    KvStoreInput,
    PerformanceSummary,
    QueryExplanation,
    QueryMetadata,
    SqliteTestResult,
    TableInfo,
    TableNameInput,
    TestStepResult,
    TransactionIdInput,
    TransactionResult,
    TypedSqlParam,
)  # noqa: F401


# kv_read Read a JSON value from the key-value database
# It takes input of KvReadInput ()
# And it returns an output Optional[dict] (The stored JSON value, or null if not found)
@extism.import_fn("extism:host/user", "kv_read")
def _kv_read(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def kv_read(input: KvReadInput) -> Optional[dict]:  # pyright: ignore [reportReturnType]
    return Optional[dict].from_json(_kv_read(input.to_json()))


# kv_store Store a JSON value in the key-value database
# It takes input of KvStoreInput ()
# And it returns an output bool (No return value - operation success indicated by lack of error)
@extism.import_fn("extism:host/user", "kv_store")
def _kv_store(input: str) -> bytes:  # pyright: ignore [reportReturnType]
    pass


def kv_store(input: KvStoreInput) -> bool:  # pyright: ignore [reportReturnType]
    return _kv_store(input.to_json())


# sqlite_begin_transaction Begin a database transaction
# It takes input of EmptyInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_begin_transaction")
def _sqlite_begin_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_begin_transaction(input: EmptyInput) -> TransactionResult:  # pyright: ignore [reportReturnType]
    return TransactionResult.from_json(_sqlite_begin_transaction(input.to_json()))


# sqlite_commit_transaction Commit a database transaction
# It takes input of TransactionIdInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_commit_transaction")
def _sqlite_commit_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_commit_transaction(input: TransactionIdInput) -> TransactionResult:  # pyright: ignore [reportReturnType]
    return TransactionResult.from_json(_sqlite_commit_transaction(input.to_json()))


# sqlite_describe_table Get detailed information about a table structure
# It takes input of TableNameInput ()
# And it returns an output TableInfo ()
@extism.import_fn("extism:host/user", "sqlite_describe_table")
def _sqlite_describe_table(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_describe_table(input: TableNameInput) -> TableInfo:  # pyright: ignore [reportReturnType]
    return TableInfo.from_json(_sqlite_describe_table(input.to_json()))


# sqlite_execute_enhanced Execute a SQL statement with enhanced metadata and type support
# It takes input of EnhancedSqlParams ()
# And it returns an output EnhancedSqlResult ()
@extism.import_fn("extism:host/user", "sqlite_execute_enhanced")
def _sqlite_execute_enhanced(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_execute_enhanced(input: EnhancedSqlParams) -> EnhancedSqlResult:  # pyright: ignore [reportReturnType]
    return EnhancedSqlResult.from_json(_sqlite_execute_enhanced(input.to_json()))


# sqlite_explain_query Get query execution plan for debugging and optimization
# It takes input of EnhancedSqlParams ()
# And it returns an output QueryExplanation ()
@extism.import_fn("extism:host/user", "sqlite_explain_query")
def _sqlite_explain_query(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_explain_query(input: EnhancedSqlParams) -> QueryExplanation:  # pyright: ignore [reportReturnType]
    return QueryExplanation.from_json(_sqlite_explain_query(input.to_json()))


# sqlite_get_stats Get database performance statistics
# It takes input of EmptyInput ()
# And it returns an output DatabaseStats ()
@extism.import_fn("extism:host/user", "sqlite_get_stats")
def _sqlite_get_stats(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_get_stats(input: EmptyInput) -> DatabaseStats:  # pyright: ignore [reportReturnType]
    return DatabaseStats.from_json(_sqlite_get_stats(input.to_json()))


# sqlite_list_tables List all tables in the database
# It takes input of EmptyInput ()
# And it returns an output str (JSON array of table names)
@extism.import_fn("extism:host/user", "sqlite_list_tables")
def _sqlite_list_tables(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_list_tables(input: EmptyInput) -> str:  # pyright: ignore [reportReturnType]
    return json.loads(_sqlite_list_tables(input.to_json()))


# sqlite_query_enhanced Execute a SQL query with enhanced metadata and type support
# It takes input of EnhancedSqlParams ()
# And it returns an output EnhancedSqlResult ()
@extism.import_fn("extism:host/user", "sqlite_query_enhanced")
def _sqlite_query_enhanced(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_query_enhanced(input: EnhancedSqlParams) -> EnhancedSqlResult:  # pyright: ignore [reportReturnType]
    return EnhancedSqlResult.from_json(_sqlite_query_enhanced(input.to_json()))


# sqlite_rollback_transaction Rollback a database transaction
# It takes input of TransactionIdInput ()
# And it returns an output TransactionResult ()
@extism.import_fn("extism:host/user", "sqlite_rollback_transaction")
def _sqlite_rollback_transaction(input: str) -> str:  # pyright: ignore [reportReturnType]
    pass


def sqlite_rollback_transaction(input: TransactionIdInput) -> TransactionResult:  # pyright: ignore [reportReturnType]
    return TransactionResult.from_json(_sqlite_rollback_transaction(input.to_json()))
