// THIS FILE WAS GENERATED BY `xtp-rust-bindgen`. DO NOT EDIT.

#![allow(non_snake_case)]
#![allow(unused_macros)]
use extism_pdk::*;

#[allow(unused)]
fn panic_if_key_missing() -> ! {
    panic!("missing key");
}

pub(crate) mod internal {
    pub(crate) fn return_error(e: extism_pdk::Error) -> i32 {
        let err = format!("{:?}", e);
        let mem = extism_pdk::Memory::from_bytes(&err).unwrap();
        unsafe {
            extism_pdk::extism::error_set(mem.offset());
        }
        -1
    }
}

#[allow(unused)]
macro_rules! try_input {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(x) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

#[allow(unused)]
macro_rules! try_input_json {
    () => {{
        let x = extism_pdk::input();
        match x {
            Ok(extism_pdk::Json(x)) => x,
            Err(e) => return internal::return_error(e),
        }
    }};
}

use base64_serde::base64_serde_type;

base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

mod exports {
    use super::*;

    #[no_mangle]
    pub extern "C" fn testEnhancedSql() -> i32 {
        let ret = crate::test_enhanced_sql(try_input!())
            .and_then(|x| extism_pdk::output(extism_pdk::Json(x)));

        match ret {
            Ok(()) => 0,
            Err(e) => internal::return_error(e),
        }
    }
}

pub mod types {
    use super::*;

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct ColumnInfo {
        /// Whether this column auto-increments
        #[serde(rename = "autoIncrement")]
        pub auto_increment: bool,

        /// Default value for the column
        #[serde(rename = "defaultValue")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub default_value: Option<String>,

        /// Column name
        #[serde(rename = "name")]
        pub name: String,

        /// Whether the column can contain NULL values
        #[serde(rename = "nullable")]
        pub nullable: bool,

        /// Whether this column is part of the primary key
        #[serde(rename = "primaryKey")]
        pub primary_key: bool,

        /// Column SQL type (e.g., TEXT, INTEGER, REAL)
        #[serde(rename = "type")]
        pub r#type: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct DatabaseStats {
        /// Average execution time per query
        #[serde(rename = "averageExecutionTimeMs")]
        pub average_execution_time_ms: f64,

        /// Database size in bytes
        #[serde(rename = "databaseSizeBytes")]
        pub database_size_bytes: i64,

        /// Count of queries by type (SELECT, INSERT, etc.)
        #[serde(rename = "queryCountByType")]
        pub query_count_by_type: serde_json::Map<String, serde_json::Value>,

        /// SQLite version string
        #[serde(rename = "sqliteVersion")]
        pub sqlite_version: String,

        /// Total execution time across all queries
        #[serde(rename = "totalExecutionTimeMs")]
        pub total_execution_time_ms: f64,

        /// Total number of queries executed
        #[serde(rename = "totalQueries")]
        pub total_queries: i64,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct EmptyInput {
        /// Dummy field to satisfy schema requirements
        #[serde(rename = "_dummy")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub _dummy: Option<String>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct EnhancedSqlParams {
        /// Array of typed SQL parameters
        #[serde(rename = "params")]
        pub params: Vec<types::TypedSqlParam>,

        /// The SQL statement or query to execute
        #[serde(rename = "sql")]
        pub sql: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct EnhancedSqlResult {
        /// Information about result columns
        #[serde(rename = "columns")]
        pub columns: Vec<types::ColumnInfo>,

        /// Array of result rows as JSON objects
        #[serde(rename = "data")]
        pub data: Vec<serde_json::Map<String, serde_json::Value>>,

        /// Query execution metadata
        #[serde(rename = "metadata")]
        pub metadata: types::QueryMetadata,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct IndexInfo {
        /// Columns included in the index
        #[serde(rename = "columns")]
        pub columns: Vec<String>,

        /// Index name
        #[serde(rename = "name")]
        pub name: String,

        /// Whether this is a unique index
        #[serde(rename = "unique")]
        pub unique: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct KvReadInput {
        /// The key to read the value for
        #[serde(rename = "key")]
        pub key: String,

        /// The table name to read from
        #[serde(rename = "table")]
        pub table: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct KvStoreInput {
        /// The key to store the value under
        #[serde(rename = "key")]
        pub key: String,

        /// The table name to store the value in
        #[serde(rename = "table")]
        pub table: String,

        /// The JSON value to store
        #[serde(rename = "value")]
        pub value: serde_json::Map<String, serde_json::Value>,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct PerformanceSummary {
        /// Average execution time per query
        #[serde(rename = "averageQueryTimeMs")]
        pub average_query_time_ms: f64,

        /// List of database operations performed
        #[serde(rename = "databaseOperations")]
        pub database_operations: Vec<String>,

        /// The fastest database operation
        #[serde(rename = "fastestOperation")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub fastest_operation: Option<String>,

        /// The slowest database operation
        #[serde(rename = "slowestOperation")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub slowest_operation: Option<String>,

        /// Total time for all operations
        #[serde(rename = "totalExecutionTimeMs")]
        pub total_execution_time_ms: f64,

        /// Total number of SQL operations performed
        #[serde(rename = "totalQueries")]
        pub total_queries: i64,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct QueryExplanation {
        /// Estimated query cost (if available)
        #[serde(rename = "estimatedCost")]
        pub estimated_cost: f64,

        /// Estimated number of rows (if available)
        #[serde(rename = "estimatedRows")]
        pub estimated_rows: i64,

        /// Human-readable query execution plan
        #[serde(rename = "queryPlan")]
        pub query_plan: String,

        /// SQLite version string
        #[serde(rename = "sqliteVersion")]
        pub sqlite_version: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct QueryMetadata {
        /// Query execution time in milliseconds
        #[serde(rename = "executionTimeMs")]
        pub execution_time_ms: f64,

        /// Row ID of the last inserted row (for INSERT statements)
        #[serde(rename = "lastInsertRowid")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub last_insert_rowid: Option<i64>,

        /// SQLite query execution plan
        #[serde(rename = "queryPlan")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub query_plan: Option<String>,

        /// Number of rows affected by the statement
        #[serde(rename = "rowsAffected")]
        pub rows_affected: i64,

        /// Number of rows returned by the query
        #[serde(rename = "rowsReturned")]
        pub rows_returned: i64,

        /// SQLite version string
        #[serde(rename = "sqliteVersion")]
        pub sqlite_version: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub enum SqlTypeHint {
        #[default]
        #[serde(rename = "text")]
        Text,
        #[serde(rename = "integer")]
        Integer,
        #[serde(rename = "real")]
        Real,
        #[serde(rename = "blob")]
        Blob,
        #[serde(rename = "boolean")]
        Boolean,
        #[serde(rename = "datetime")]
        Datetime,
        #[serde(rename = "_null")]
        _null,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct SqliteTestResult {
        /// Error message if test failed
        #[serde(rename = "errorMessage")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub error_message: Option<String>,

        /// Overall performance metrics
        #[serde(rename = "performanceSummary")]
        pub performance_summary: types::PerformanceSummary,

        /// Individual test results
        #[serde(rename = "results")]
        pub results: Vec<types::TestStepResult>,

        /// Whether all tests passed successfully
        #[serde(rename = "success")]
        pub success: bool,

        /// Name of the test that was executed
        #[serde(rename = "testName")]
        pub test_name: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TableInfo {
        /// Table columns
        #[serde(rename = "columns")]
        pub columns: Vec<types::ColumnInfo>,

        /// Table indexes
        #[serde(rename = "indexes")]
        pub indexes: Vec<types::IndexInfo>,

        /// Table name
        #[serde(rename = "name")]
        pub name: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TableNameInput {
        /// Name of the table
        #[serde(rename = "tableName")]
        pub table_name: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TestStepResult {
        /// Additional details about the test step
        #[serde(rename = "details")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub details: Option<serde_json::Map<String, serde_json::Value>>,

        /// Error message if step failed
        #[serde(rename = "errorMessage")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub error_message: Option<String>,

        /// Time taken for this step
        #[serde(rename = "executionTimeMs")]
        pub execution_time_ms: f64,

        /// Name of the test step
        #[serde(rename = "stepName")]
        pub step_name: String,

        /// Whether this step passed
        #[serde(rename = "success")]
        pub success: bool,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TransactionIdInput {
        /// Transaction identifier
        #[serde(rename = "transactionId")]
        pub transaction_id: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TransactionResult {
        /// Whether the transaction operation succeeded
        #[serde(rename = "success")]
        pub success: bool,

        /// Transaction identifier
        #[serde(rename = "transactionId")]
        pub transaction_id: String,
    }

    #[derive(
        Default,
        Debug,
        Clone,
        serde::Serialize,
        serde::Deserialize,
        extism_pdk::FromBytes,
        extism_pdk::ToBytes,
    )]
    #[encoding(Json)]
    pub struct TypedSqlParam {
        /// Optional type hint for the parameter
        #[serde(rename = "typeHint")]
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(default)]
        pub type_hint: Option<types::SqlTypeHint>,

        /// The parameter value (can be string, number, boolean, null, etc.)
        #[serde(rename = "value")]
        pub value: serde_json::Map<String, serde_json::Value>,
    }
}

mod raw_imports {
    use super::*;
    #[host_fn]
    extern "ExtismHost" {

        pub(crate) fn kv_read(
            input: Json<types::KvReadInput>,
        ) -> Json<Option<serde_json::Map<String, serde_json::Value>>>;

        pub(crate) fn kv_store(input: Json<types::KvStoreInput>) -> bool;

        pub(crate) fn sqlite_begin_transaction(
            input: Json<types::EmptyInput>,
        ) -> Json<types::TransactionResult>;

        pub(crate) fn sqlite_commit_transaction(
            input: Json<types::TransactionIdInput>,
        ) -> Json<types::TransactionResult>;

        pub(crate) fn sqlite_describe_table(
            input: Json<types::TableNameInput>,
        ) -> Json<types::TableInfo>;

        pub(crate) fn sqlite_execute_enhanced(
            input: Json<types::EnhancedSqlParams>,
        ) -> Json<types::EnhancedSqlResult>;

        pub(crate) fn sqlite_explain_query(
            input: Json<types::EnhancedSqlParams>,
        ) -> Json<types::QueryExplanation>;

        pub(crate) fn sqlite_get_stats(
            input: Json<types::EmptyInput>,
        ) -> Json<types::DatabaseStats>;

        pub(crate) fn sqlite_list_tables(input: Json<types::EmptyInput>) -> Json<String>;

        pub(crate) fn sqlite_query_enhanced(
            input: Json<types::EnhancedSqlParams>,
        ) -> Json<types::EnhancedSqlResult>;

        pub(crate) fn sqlite_rollback_transaction(
            input: Json<types::TransactionIdInput>,
        ) -> Json<types::TransactionResult>;

    }
}

/// kv_read Read a JSON value from the key-value database
/// It takes input of types::KvReadInput ()
/// And it returns an output Option<serde_json::Map<String, serde_json::Value>> (The stored JSON value, or null if not found)
#[allow(unused)]
pub(crate) fn kv_read(
    input: types::KvReadInput,
) -> std::result::Result<Option<serde_json::Map<String, serde_json::Value>>, extism_pdk::Error> {
    let res = unsafe { raw_imports::kv_read(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// kv_store Store a JSON value in the key-value database
/// It takes input of types::KvStoreInput ()
/// And it returns an output bool (No return value - operation success indicated by lack of error)
#[allow(unused)]
pub(crate) fn kv_store(input: types::KvStoreInput) -> std::result::Result<bool, extism_pdk::Error> {
    let res = unsafe { raw_imports::kv_store(extism_pdk::Json(input))? };

    Ok(res)
}

/// sqlite_begin_transaction Begin a database transaction
/// It takes input of types::EmptyInput ()
/// And it returns an output types::TransactionResult ()
#[allow(unused)]
pub(crate) fn sqlite_begin_transaction(
    input: types::EmptyInput,
) -> std::result::Result<types::TransactionResult, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_begin_transaction(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_commit_transaction Commit a database transaction
/// It takes input of types::TransactionIdInput ()
/// And it returns an output types::TransactionResult ()
#[allow(unused)]
pub(crate) fn sqlite_commit_transaction(
    input: types::TransactionIdInput,
) -> std::result::Result<types::TransactionResult, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_commit_transaction(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_describe_table Get detailed information about a table structure
/// It takes input of types::TableNameInput ()
/// And it returns an output types::TableInfo ()
#[allow(unused)]
pub(crate) fn sqlite_describe_table(
    input: types::TableNameInput,
) -> std::result::Result<types::TableInfo, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_describe_table(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_execute_enhanced Execute a SQL statement with enhanced metadata and type support
/// It takes input of types::EnhancedSqlParams ()
/// And it returns an output types::EnhancedSqlResult ()
#[allow(unused)]
pub(crate) fn sqlite_execute_enhanced(
    input: types::EnhancedSqlParams,
) -> std::result::Result<types::EnhancedSqlResult, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_execute_enhanced(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_explain_query Get query execution plan for debugging and optimization
/// It takes input of types::EnhancedSqlParams ()
/// And it returns an output types::QueryExplanation ()
#[allow(unused)]
pub(crate) fn sqlite_explain_query(
    input: types::EnhancedSqlParams,
) -> std::result::Result<types::QueryExplanation, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_explain_query(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_get_stats Get database performance statistics
/// It takes input of types::EmptyInput ()
/// And it returns an output types::DatabaseStats ()
#[allow(unused)]
pub(crate) fn sqlite_get_stats(
    input: types::EmptyInput,
) -> std::result::Result<types::DatabaseStats, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_get_stats(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_list_tables List all tables in the database
/// It takes input of types::EmptyInput ()
/// And it returns an output String (JSON array of table names)
#[allow(unused)]
pub(crate) fn sqlite_list_tables(
    input: types::EmptyInput,
) -> std::result::Result<String, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_list_tables(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_query_enhanced Execute a SQL query with enhanced metadata and type support
/// It takes input of types::EnhancedSqlParams ()
/// And it returns an output types::EnhancedSqlResult ()
#[allow(unused)]
pub(crate) fn sqlite_query_enhanced(
    input: types::EnhancedSqlParams,
) -> std::result::Result<types::EnhancedSqlResult, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_query_enhanced(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}

/// sqlite_rollback_transaction Rollback a database transaction
/// It takes input of types::TransactionIdInput ()
/// And it returns an output types::TransactionResult ()
#[allow(unused)]
pub(crate) fn sqlite_rollback_transaction(
    input: types::TransactionIdInput,
) -> std::result::Result<types::TransactionResult, extism_pdk::Error> {
    let res = unsafe { raw_imports::sqlite_rollback_transaction(extism_pdk::Json(input))? };

    let extism_pdk::Json(res) = res;

    Ok(res)
}
